name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t test .

    - name: Push Docker image to DockerHub
      run: |
        docker tag test shru2317/test:latest
        docker push shru2317/test:latest

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Deploy Docker image to EC2 instance
      run: |
        hostname -i 
        ssh -o StrictHostKeyChecking=no ec2-user@54.87.177.162 "docker pull shru2317/test:latest && docker stop nginx && docker rm nginx && docker run -d -p 80:80 --name nginx shru2317/test:latest"
